language: node_js
node_js:
  - '10'
env: secure
  DB_URL = MTJgUZ6S+oPYXHpDESYGeUXTmwkd0tfZMc2uq/wsnjgCZRhE+r08wNSk20RZNFTmg7sPYU/LCI01fRbj2nN1xXLDCRDOO/AgUY2PzdLaP74DMJwbKOUFiVECwkbHmri9bOSndNVN79hsWSN6nxxkefpStqpmT+mrVUU0/rAkDkEuInvmUYod884WRIsSXrl0k2xLEfHY9/6E5sZVTGEo+En2rJm3I5ygwNxnJQNEJHcQq3mJRGHoBus/kkLBoEuqqlG1oFB6zpQcS1ucRAPFNl9UtJQ6fstIIJ09Ukwto8+MlvQsOe3lDItn03bE4YXqS+/NpEAmsw1fR+rFMUCMjGvq8klACJ6/s0/sJ4XfkXlF15p+rpIOmdMdcGgM9vG1ajzBd2THLx11XKuBAwygXg/ie24fk5yMkTDu25gMM3nh5XOxoYDykdNA8zujIoiExqTqTIIHluEThU24talQ5AWcm4DOWShuIzDQ5ZKJ9TfPodDDdp8f7QMeiBAAJfu4cBz5j9D5h3DgrPqOUQOpPDGLRjcyOQP2hRGYnqc0ubDD0MsExVeOFQUMjipdIrl+wDx0TJtfBBlpoqrPI3X+7a0wOVl7Wb7Yyw3l8gRcwsorkJ5k7PLU5CnS0aC29yqT5FFQtB6VR/vbg8o533Nhh9akE4NZGxlyyVmQyitLCeI=
  BUILD_ID = TRAVIS_BUILD_ID
  BUILD_NUM = TRAVIS_BUILD_NUMBER
  JOB_NUM = TRAVIS_JOB_ID
  BRANCH = TRAVIS_BRANCH

script:
  - npm install
  - node mongotest.js
